version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifier